---
title: "Major-Assignment 2"
author: "Subhrajit Guhathakurta & Uijeong Hwang"
date: '2023-10-19'
output:
  rmdformats::downcute:
    downcute_theme: "chaos"
    code_folding: show
---

<style type="text/css">
  body{
  font-family: Arial;
  }
</style>

# Instructions

A regional transit agency is interested in assessing how long it takes for people in different parts of Atlanta who park-n-ride to travel from their home to the major employment center (e.g., Midtown) and understanding if there is any disparities across neighborhoods. 

You are tasked to perform this calculation of travel time using data from OSM, GTFS, and Census. This assignment provides a code template (download it from [here](https://ujhwang.github.io/UrbanAnalytics2023/Assignment/major_2/major_assignment_2_template.Rmd)). The template will explain how to use the template, what tasks you will be performing, and detailed steps. Understanding how to use the template may take some time, so start early.

# Logistics
1. Write your report and R code in a R Markdown document. 
2. Use the Knit button in R Studio to render it as a HTML document.
3. Publish the rendered document to RPubs.
4. <font color="pink">Submit the URL of the RPubs document through Canvas by **11/02/2023 Thursday midnight (11:59 PM on Thursday).** </font>
5. To submit, go to Canvas > Assignments > Major assignment 2.
6. Grades and feedback will be posted through Canvas.



    
# Notes
Try Knitting your R Markdown document and publishing it on RPubs early. This is to ensure you'd have time to troubleshoot if you encounter technical issues.

You can always replace a published document (i.e., republish) or delete the existing one and publish it as a new document. 