---
title: "Computer vision"
author: "Originally written by Bon Woo Koo & Subhro Guhathakurta; modified by Uijeong Hwang"
date: '2023-10-26'
output:
  rmdformats::downcute:
    downcute_theme: "chaos"
---

<style type="text/css">
  body{
  font-family: Arial;
  }
</style>

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(magrittr)
library(osmdata)
library(sfnetworks)
library(units)
library(sf)
library(tidygraph)
library(tmap)
library(here)
ttm()
```

## Merge the data processed from Colab back to R. 

```{r}
# Load the sampled points. You need to change the following command.
endp <- st_read(here("Lab", "Module_4", "endp_chamblee.geojson"))

# Download the output from the computer vision models. You may need to change the following command.
seg_output <- read.csv(here("Lab", "Module_4", "seg_output.csv"))

# Join them back to the `endp` object that was used to download images.
seg_output_nodes <- endp %>% inner_join(seg_output, by=c("node_id"="img_id"))

seg_output_nodes
```

## Calculate Greenness.
```{r}
seg_output_nodes %<>% 
  mutate(greenness = tree + grass + plant,
         pct_greenness = greenness/(640*640))

# Map!
t1 <- tm_basemap("OpenStreetMap")+
  tm_shape(seg_output_nodes) + 
  tm_dots(col = "pct_greenness", style="quantile", palette = 'viridis')

t2 <- tm_basemap(leaflet::providers$Esri.WorldImagery) +
  tm_shape(seg_output_nodes %>% st_bbox() %>% st_as_sfc()) + 
  tm_borders(alpha = 0)

tmap_arrange(t1, t2, sync = T)
```

## Calculate Building-to-street Ratio.
```{r}
seg_output_nodes %<>% 
  mutate(b2s_ratio = (building + house)/(sidewalk + road + car)) %>% 
  mutate(b2s_ratio = case_when(
    is.infinite(b2s_ratio) ~ 0,
    TRUE ~ b2s_ratio))

tm_shape(seg_output_nodes) + 
  tm_dots(col = "b2s_ratio", style="quantile", palette = 'viridis')
```

## Are there any differences by type of road?
```{r}
seg_output_road_type <- seg_output_nodes %>% 
  st_drop_geometry() %>% 
  mutate(highway = case_when(
    highway == 'trunk' ~ 'trunk',
    highway == 'primary' ~ 'pri',
    highway == 'secondary' ~ 'sec',
    highway == 'tertiary' ~ 'ter',
    highway == 'residential' ~ 'res',
    highway == 'unclassified' ~ 'unc',
    TRUE ~ NA_character_)) %>% 
  filter(!is.na(highway)) %>% 
  mutate(highway = factor(highway, levels = c('trunk','pri','sec','ter','res','unc'))) %>% 
  group_by(highway) %>% 
  summarise(across(c("building", "greenness", "road", "sidewalk", "sky", "car"), ~ round(mean(.x)/(640^2), 4)))

seg_output_nodes %>% 
  pivot_longer(cols = c(building, sky, greenness, road, sidewalk, car), 
               names_to = 'variable', 
               values_to = "value") %>% 
  ggplot() +
  geom_boxplot(mapping = aes(x = highway, y = value), outlier.shape = NA) +
  theme_bw() +
  facet_wrap(~variable, scales = "free_y")
```










