---
title: "UA2022-Twit"
author: "Bonwoo Koo"
date: '2022-07-07'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
if (!'rtweet' %in% installed.packages()){
  install.packages('rtweet', dependencies = T)
} else {
  library(rtweet)
}
```

# Setting the twitter access tokens

Twitter developer account needed

```{r pressure, echo=FALSE}
# whatever name you assigned to your created app
appname <- Sys.getenv('twit_app')

# create token named "twitter_token"
# the keys used should be replaced by your own keys obtained by creating the app  

twitter_token <- create_token(
  app = appname,
  consumer_key = Sys.getenv("twit_apikey"),
  consumer_secret = Sys.getenv("twit_apisecret"),
  access_token = Sys.getenv('twit_accesstoken'),
  access_secret = Sys.getenv("twit_accesstokensecret"))
```

# Search tweets

```{r}
# q: Query to be searched, used to filter and select tweets to return from Twitter's REST API. Must be a character string not to exceed maximum of 500 characters. Spaces behave like boolean "AND" operator. To search for tweets containing at least one of multiple possible terms, separate each search term with spaces and "OR" (in caps). For example, the search q = "data science" looks for tweets containing both "data" and "science" located anywhere in the tweets and in any order. When "OR" is entered between search terms, query = "data OR science", Twitter's REST API should return any tweet that contains either "data" or "science." It is also possible to search for exact phrases using double quotes. To do this, either wrap single quotes around a search query using double quotes, e.g., q = '"data science"' or escape each internal double quote with a single backslash, e.g., q = "\"data science\"".

# n: Integer, specifying the total number of desired tweets to return. Defaults to 100. Maximum number of tweets returned from a single token is 18,000. To return more than 18,000 tweets, users are encouraged to set retryonratelimit to TRUE. See details for more information.
twt <- search_tweets(q = "beltline", geocode = "33.74,-84.39,30mi", n = 200)
```

Let's understand what comes along in the search results. To do so, we can use `str()` function to see the structure of the returned object.

```{r}
print(twt, width = 1000)
```

Some columns contain lists!
Some columns are empty!

```{r}
twt.c <- twt[,sapply(twt, function(x) sum(is.na(x)) == 0)]

twt_fl <- rtweet::flatten(twt.c)
```

