---
title: "Mini-Assignment 3"
author: "Subhrajit Guhathakurta & Uijeong Hwang"
date: '2023-9-19'
output:
  rmdformats::downcute:
    downcute_theme: "chaos"
    code_folding: show
---

<style type="text/css">
  body{
  font-family: Arial;
  }
</style>

# Instructions
In this mini-assignment, you get to build upon the code you implemented so far and include aspects of the Week 5 lectures on Exploratory Data Analysis.

For this assignment, imagine that you are a bicycle enthusiast and want to set up a bicycle rental store in a place within Fulton and Dekalb counties. The question in your mind is about where this store should be located. You realize that you can get the locations of all bike rental stores from Yelp API (categories: bikerentals). Another data that might help you could be the census data showing how many commuters commute on a bike (which could be a proxy for bike-friendliness of a community and environment). Here you will be looking for places where there is gap between bike stores (rentals in this case - but hopefully these also have other bike related services) and tracts with bike commuters.


**To complete this assignment, follow the directions below:**

1. Download Yelp data on categories = bikerentals for Atlanta metro.
    * If you encounter issues in API requests, try Sys.sleep() as you see appropriate.
    * Remember to save the downloaded Yelp data in your hard drive to avoid making excessive API requests. Once you've downloaded the data, you can simply read the Yelp data from your hard drive and proceed from there.
    * However, even when you've stopped using the code for downloading Yelp data, do not delete them from your RMD; instructors need to see the entire code. You can use code chunk option {r, eval=FALSE} to keep the code for downloading Yelp in your RMD but not actually run it. Read [this](https://rpubs.com/Lingling912/870659) to learn more.
2. Download  census data for the commuting (and other variables that you may choose to use).
3. Tidy your data by:
    * Deleting duplicated rows.
    * Flattening nested columns that have multiple variables in one column. Pay particular attention to the “category” column.
    * Delete rows that have missing data in coordinates variable and other variables of interest. It’s okay to have NAs in variables that are not of interest.
    * Delete rows that fall outside of the boundary of your choice.
4. Examine the associations among the variables bike rentals and bike commuting. Find the right metrics (you may need to create new variables e.g., proportion, density, etc.). 
    * Show at least one graph and at least one map with two variables that you are interested in examining (you can do more!).

# Logistics
1. Write your report and R code in a R Markdown document. 
2. Use the Knit button in R Studio to render it as a HTML document.
3. Publish the rendered document to RPubs.
4. <font color="pink">Submit the URL of the RPubs document through Canvas by **9/28/2023 Thursday midnight (11:59 PM on Thursday).** </font>
5. To submit, go to Canvas > Assignments > Mini assignment 3.
6. Grades and feedback will be posted through Canvas.



    
# Notes
Try Knitting your R Markdown document and publishing it on RPubs early. This is to ensure you'd have time to troubleshoot if you encounter technical issues.

You can always replace a published document (i.e., republish) or delete the existing one and publish it as a new document. 